export const mockActivity: any[] = []
export const mockProperties: any[] = []
export const mockDocuments: any[] = []
export const mockInspections: any[] = []
export const mockManagerApprovals: any[] = []
export const mockLegalCases: any[] = []
